// Auto-generated
let project = new Project('virtualwallproject');

project.addSources('Sources');
project.addLibrary("../../../Documents/Programming/ArmorySDK/armory");
project.addLibrary("../../../Documents/Programming/ArmorySDK/iron");
project.addParameter('--no-inline');
project.addParameter('-dce full');
project.addParameter('arm.FrameTrait');
project.addParameter("--macro keep('arm.FrameTrait')");
project.addParameter('arm.HiddenTrait');
project.addParameter("--macro keep('arm.HiddenTrait')");
project.addParameter('arm.SlaveFrameTrait');
project.addParameter("--macro keep('arm.SlaveFrameTrait')");
project.addParameter('arm.MasterFrameTrait');
project.addParameter("--macro keep('arm.MasterFrameTrait')");
project.addParameter('arm.KeyboardSendEvents');
project.addParameter("--macro keep('arm.KeyboardSendEvents')");
project.addParameter('arm.LightTrait');
project.addParameter("--macro keep('arm.LightTrait')");
project.addParameter('arm.SceneTrait');
project.addParameter("--macro keep('arm.SceneTrait')");
project.addParameter('arm.StartTrait');
project.addParameter("--macro keep('arm.StartTrait')");
project.addParameter('arm.SurfaceSendEvents');
project.addParameter("--macro keep('arm.SurfaceSendEvents')");
project.addParameter('arm.CameraTrait');
project.addParameter("--macro keep('arm.CameraTrait')");
project.addParameter('arm.InfoTrait');
project.addParameter("--macro keep('arm.InfoTrait')");
project.addParameter('arm.ScreenSequenceTrait');
project.addParameter("--macro keep('arm.ScreenSequenceTrait')");
project.addParameter('arm.TrayTrait');
project.addParameter("--macro keep('arm.TrayTrait')");
project.addParameter('arm.JsonWallTrait');
project.addParameter("--macro keep('arm.JsonWallTrait')");
project.addParameter('arm.InTheWayTrait');
project.addParameter("--macro keep('arm.InTheWayTrait')");
project.addShaders("build_b20200818/compiled/Shaders/*.glsl", { noembed: false});
project.addAssets("build_b20200818/compiled/Assets/**", { notinlist: true });
project.addAssets("build_b20200818/compiled/Shaders/*.arm", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/brdf.png", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_0.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_1.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_2.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_3.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_4.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_5.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_6.hdr", { notinlist: true });
project.addAssets("../../Documents/Programming/ArmorySDK/armory/Assets/hosek/hosek_radiance_7.hdr", { notinlist: true });
project.addDefine('arm_hosek');
project.addDefine('rp_renderer=Forward');
project.addDefine('rp_shadowmap');
project.addDefine('rp_shadowmap_cascade=1024');
project.addDefine('rp_shadowmap_cube=512');
project.addDefine('rp_background=World');
project.addDefine('kha_no_ogg');
project.addDefine('arm_published');
project.addDefine('arm_soundcompress');
project.addDefine('arm_skin');
project.addDefine('arm_particles');
project.addDefine('arm_loadscreen');
project.addDefine('arm_resizable');
project.addAssets('Assets/**');

resolve(project);
